apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  labels:
    name: spring-config
data:
  prometheus.yml: |
      {
        global:
          scrape_interval:     15s
          evaluation_interval: 15s
        rule_files:
        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
            - targets: ['127.0.0.1:9090']

          - job_name: 'spring-actuator'
            metrics_path: '/actuator/prometheus'
            scrape_interval: 5s
            static_configs:
            - targets: ['<Spring IP>:8080']
      }

---




apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          # env:
          #   - name: MONGO_URL
          #     value: mongodb://mongo:27017
          # imagePullPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: spring-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer
